name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout secrets repository
        uses: actions/checkout@v2
        with:
          repository: TylerStrel/secrets 
          path: secrets 

  deploy:
    needs: fetch-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Read Secrets
        id: read-secrets
        run: |
          echo "::set-output name=SERVER_HOST::$(yaml getValue secrets/secrets.yml SERVER_HOST)"
          echo "::set-output name=SERVER_USER::$(yaml getValue secrets/secrets.yml SERVER_USER)"
          echo "::set-output name=SSH_PRIVATE_KEY::$(yaml getValue secrets/secrets.yml SSH_PRIVATE_KEY)"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.read-secrets.outputs.SERVER_HOST }}
          username: ${{ steps.read-secrets.outputs.SERVER_USER }}
          key: ${{ steps.read-secrets.outputs.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/personal-portfolio/Hundo
            ./deploy.sh
